"""create test column for orderitems tabel

Revision ID: 94f62b4a51a2
Revises: b935ecae57bf
Create Date: 2026-09-13 02:41:19.738841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f62b4a51a2'
down_revision: Union[str, Sequence[str], None] = 'b935ecae57bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('test', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'test')
    # ### end Alembic commands ###
