"""remove test column

Revision ID: e190b7b5a4d9
Revises: 94f62b4a51a2
Create Date: 2026-09-13 02:43:12.059267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e190b7b5a4d9'
down_revision: Union[str, Sequence[str], None] = '94f62b4a51a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('test', sa.FLOAT(), nullable=False))
    # ### end Alembic commands ###
